name: safe_gen
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - ncurses=6.5
  - openssl=3.0.17
  - pip=25.1
  - pthread-stubs=0.3
  - python=3.11.13
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - accelerate==1.10.0
      - annotated-types==0.7.0
      - asttokens==3.0.0
      - av==15.0.0
      - bitsandbytes==0.46.1
      - certifi==2025.8.3
      - charset-normalizer==3.4.2
      - contourpy==1.3.3
      - cycler==0.12.1
      - decorator==5.2.1
      - deepspeed==0.17.4
      - diffusers==0.35.0.dev0
      - einops==0.8.1
      - executing==2.2.0
      - filelock==3.18.0
      - fonttools==4.59.0
      - fsspec==2025.7.0
      - hf-xet==1.1.5
      - hjson==3.1.0
      - huggingface-hub==0.34.3
      - idna==3.10
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - ipdb==0.13.13
      - ipython==9.4.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - markupsafe==3.0.2
      - matplotlib==3.10.5
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - msgpack==1.1.1
      - networkx==3.5
      - ninja==1.11.1.4
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.3.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.3.0
      - prompt-toolkit==3.0.51
      - protobuf==6.31.1
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - qwen-vl-utils==0.0.11
      - regex==2025.7.34
      - requests==2.32.4
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scipy==1.16.1
      - sentencepiece==0.2.0
      - six==1.17.0
      - stack-data==0.6.3
      - sympy==1.14.0
      - tifffile==2025.6.11
      - timm==1.0.19
      - tokenizers==0.21.4
      - torch==2.7.1
      - torchaudio==2.7.1
      - torchvision==0.22.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.55.4
      - triton==3.3.1
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - wcwidth==0.2.13
      - xformers==0.0.31.post1
      - zipp==3.23.0
